name: CI Angular

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    

jobs:
  build_Angular:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        working-directory: Front-end/f1-information-frontend
        run: npm ci
      - name: Build
        working-directory: Front-end/f1-information-frontend
        run: npm run build -- --prod
      - name: Test
        working-directory: Front-end/f1-information-frontend
        run: npm test
        
  build_admin:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        working-directory: Front-end/Admin-app
        run: npm ci
      - name: Build
        working-directory: Front-end/Admin-app
        run: npm run build -- --prod
      - name: Test
        working-directory: Front-end/Admin-app
        run: npm test

  Docker_Build_and_Push_Action_Admin:
      runs-on: ubuntu-latest
      needs: [build_admin]

      steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
            username:  ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_ACCESSTOKEN}}
          
      - name: Build the Docker image
        working-directory: Front-end/Admin-app
        run: docker build -t teunix/my-private-repo .

      - name: tag
        run: docker tag teunix/my-private-repo:latest teunix/my-private-repo:admin

      - name: deploy Docker image to dockerhub
        run: docker push teunix/my-private-repo:admin
