name: CI Angular

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    

jobs:
  build_Angular:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        working-directory: Front-end/f1-information-frontend
        run: npm ci
      - name: Build
        working-directory: Front-end/f1-information-frontend
        run: npm run build -- --prod
      - name: Test
        working-directory: Front-end/f1-information-frontend
        run: npm test
        
  build_admin:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        working-directory: Front-end/Admin-app
        run: npm ci
      - name: Build
        working-directory: Front-end/Admin-app
        run: npm run build -- --prod
      - name: Test
        working-directory: Front-end/Admin-app
        run: npm test

  Docker_Build_and_Push_Action_Admin:
      runs-on: ubuntu-latest
      needs: [build_admin]

      steps:
      - uses: actions/checkout@v2
      
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          # Name of the Docker image
          image: 450192/Admin-app
          # Tags override for Docker image
          tags: latest
          # Target Docker registry
          registry: docker.io
          # Location of Dockerfile, if not Dockerfile in root directory
          dockerfile: Front-end/Admin-app/Dockerfile
          # Directory to run `docker build` from, if not project root
          directory: Front-end/customerapp-vue                    
          # Docker registry username
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Docker registry password
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
