name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_NetCore:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: Back-end/f1-information-backend
      run: dotnet restore
    - name: Build
      working-directory: Back-end/f1-information-backend
      run: dotnet build --no-restore
    - name: Test
      working-directory: Back-end/f1-information-backend
      run: dotnet test --no-build --verbosity normal
  build_Angular:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build -- --prod
        
