name: Docker Image CI

on:
  push:
    branches: [ Test ]
  pull_request:
    branches: [ Test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      
      run: docker build -t teunix/my-private-repo .
    
    - name: Test the Docker image
      run: docker run teunix/my-private-repo
    
    - name: login
      run: docker login
      
    - name: deploy Docker image to dockerhub
      run: docker push teunix/my-private-repo
