name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
          username:  teunix
          password: a583d209-f9cd-4b54-b098-a0041a850c50
          
    - name: Build the Docker image
      run: docker build -t teunix/my-private-repo .
      
    - name: tag
      run: docker tag teunix/my-private-repo:latest teunix/my-private-repo:myfirstimagepush
      
    - name: Test the Docker image
      run: docker run teunix/my-private-repo:myfirstimagepush
      
    - name: deploy Docker image to dockerhub
      run: docker push teunix/my-private-repo:myfirstimagepush
